### ISSUE TITLE
Provider web urls

### ISSUE THREAD

**Issue by casey** [casey/src#3]
```
providers:
  github:
    web-templates:
      main: https://github.com/{{user}}/{{repo}}
      issue: https://github.com/{{user}}/{{repo}}/issues/{{number}}
```

(To supporting going to the repo page, opening issues, etc.)
